#services:
#  db:
#    image: postgres:16
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Butterfly
#      POSTGRES_DB: tododb
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data




services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Butterfly
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migration/init_schema.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/migration/insert_admin_user.sql:/docker-entrypoint-initdb.d/02_insert_admin.sql

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Butterfly
      DB_NAME: tododb
      JWT_SECRET: supersecretkey


volumes:
  db_data:
